### ISSUE TITLE
Error while running ifttt example

### ISSUE THREAD

**Issue by upgundecha** [anki/cozmo-python-sdk#115]
Hi,

I am trying to run the IFTTT Gmail example. However, I am getting following error consistently

```
/ifttt_gmail.py
Traceback (most recent call last):
  File "./ifttt_gmail.py", line 153, in <module>
    sdk_conn = cozmo.connect_on_loop(app.loop)
  File "/Users/upgundecha/Library/Python/3.6/lib/python/site-packages/cozmo/run.py", line 548, in connect_on_loop
    transport, coz_conn = loop.run_until_complete(connect())
AttributeError: 'NoneType' object has no attribute 'run_until_complete'
```
I have ngrok running and Cozmo on charger.

Anything else missing here?

**Comment by upgundecha** [comment]
Following suggestion from @MarkWesleyAtAnki resolved the error:
```
app = web.Application(loop=asyncio.get_event_loop())
```
