### ISSUE TITLE
Sdk Eror

### ISSUE THREAD

**Issue by Xen141** [anki/cozmo-python-sdk#221]
Hello,
I have a problem ! 
if i execute command `py remote_control_cozmo.py` on windows cmd
that return 
`Traceback (most recent call last):
  File "C:\Users\voyag\Downloads\cozmo_sdk_examples\apps\remote_control_cozmo.py", line 926, in <module>
    cozmo.connect(run)
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 605, in connect
    return _connect_sync(f, conn_factory, connector)
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 527, in _connect_sync
    coz_conn = lt.start()
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 468, in start
    raise coz_conn
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 450, in run_loop
    coz_conn = connect_on_loop(self.loop, self.conn_factory, self.connector)
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 569, in connect_on_loop
    transport, coz_conn = loop.run_until_complete(connect())
  File "C:\Users\voyag\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 567, in connect
    return await connector.connect(loop, factory, conn_check)
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 377, in connect
    android_result = await self._do_connect(self.android, *conn_args)
  File "C:\Users\voyag\AppData\Roaming\Python\Python310\site-packages\cozmo\run.py", line 364, in _do_connect
    result = await asyncio.gather(connect, loop=loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'
sys:1: RuntimeWarning: coroutine 'AndroidConnector.connect' was never awaited`
im on windows 11, sdk mode is activated on cozmo app, my phone is connected to my computer and adb is actived in developer option.
Someone can help me. Please

**Comment by edenweb1** [comment]
Hi, same problem here...

**Comment by edenweb1** [comment]
[](https://github.com/anki/cozmo-python-sdk/pull/219)

**Comment by gwatts** [comment]
Python 3.10 removed `loop` from `gather` .. will likely work with an older version of Python short of the SDK itself being updated 

See also https://docs.python.org/3.10/whatsnew/3.10.html#changes-in-the-python-api

**Comment by Kaki-In** [comment]
Are we forced to use an old version or is it any update to do?
